SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
from REST_INFO 
where (FAVORITES,FOOD_TYPE) in (
    select max(FAVORITES),FOOD_TYPE
        from REST_INFO
        group by FOOD_TYPE)
order by FOOD_TYPE desc
